[versions]
agp = "8.6.1"
androidxJunit = "1.2.1"
appAutomotive = "1.4.0"
appcompatVersion = "1.7.0"
coreKtxVersion = "1.13.1"
kotlin = "1.9.0"
junit = "4.13.2"
espressoCore = "3.6.1"


[libraries]
androidx-app-automotive = { module = "androidx.car.app:app-automotive", version.ref = "appAutomotive" }
androidx-app-testing = { module = "androidx.car.app:app-testing", version.ref = "appAutomotive" }
androidx-appcompat-v151 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx-v190 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-junit-v114 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

